image: docker:latest

stages:
  - build

build-windows:
  stage: build
  image: $CI_REGISTRY/veyon/ci-mingw-w64:5.0
  script:
    - .ci/windows/build.sh $BITS
  parallel:
    matrix:
      - BITS: [32, 64]
  artifacts:
    paths: [ veyon-win* ]
    expire_in: 1 day

variables:
  GIT_SUBMODULE_STRATEGY: recursive
